/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: blinds.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "blinds.pb-c.h"
void   blnd_status__init
                     (BlndStatus         *message)
{
  static const BlndStatus init_value = BLND_STATUS__INIT;
  *message = init_value;
}
size_t blnd_status__get_packed_size
                     (const BlndStatus *message)
{
  assert(message->base.descriptor == &blnd_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t blnd_status__pack
                     (const BlndStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &blnd_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t blnd_status__pack_to_buffer
                     (const BlndStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &blnd_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BlndStatus *
       blnd_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BlndStatus *)
     protobuf_c_message_unpack (&blnd_status__descriptor,
                                allocator, len, data);
}
void   blnd_status__free_unpacked
                     (BlndStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &blnd_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   blnd_logging__init
                     (BlndLogging         *message)
{
  static const BlndLogging init_value = BLND_LOGGING__INIT;
  *message = init_value;
}
size_t blnd_logging__get_packed_size
                     (const BlndLogging *message)
{
  assert(message->base.descriptor == &blnd_logging__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t blnd_logging__pack
                     (const BlndLogging *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &blnd_logging__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t blnd_logging__pack_to_buffer
                     (const BlndLogging *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &blnd_logging__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BlndLogging *
       blnd_logging__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BlndLogging *)
     protobuf_c_message_unpack (&blnd_logging__descriptor,
                                allocator, len, data);
}
void   blnd_logging__free_unpacked
                     (BlndLogging *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &blnd_logging__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   blnd_available__init
                     (BlndAvailable         *message)
{
  static const BlndAvailable init_value = BLND_AVAILABLE__INIT;
  *message = init_value;
}
size_t blnd_available__get_packed_size
                     (const BlndAvailable *message)
{
  assert(message->base.descriptor == &blnd_available__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t blnd_available__pack
                     (const BlndAvailable *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &blnd_available__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t blnd_available__pack_to_buffer
                     (const BlndAvailable *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &blnd_available__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BlndAvailable *
       blnd_available__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BlndAvailable *)
     protobuf_c_message_unpack (&blnd_available__descriptor,
                                allocator, len, data);
}
void   blnd_available__free_unpacked
                     (BlndAvailable *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &blnd_available__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   blnd_operation_message__init
                     (BlndOperationMessage         *message)
{
  static const BlndOperationMessage init_value = BLND_OPERATION_MESSAGE__INIT;
  *message = init_value;
}
size_t blnd_operation_message__get_packed_size
                     (const BlndOperationMessage *message)
{
  assert(message->base.descriptor == &blnd_operation_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t blnd_operation_message__pack
                     (const BlndOperationMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &blnd_operation_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t blnd_operation_message__pack_to_buffer
                     (const BlndOperationMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &blnd_operation_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BlndOperationMessage *
       blnd_operation_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BlndOperationMessage *)
     protobuf_c_message_unpack (&blnd_operation_message__descriptor,
                                allocator, len, data);
}
void   blnd_operation_message__free_unpacked
                     (BlndOperationMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &blnd_operation_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   blnd_response_message__init
                     (BlndResponseMessage         *message)
{
  static const BlndResponseMessage init_value = BLND_RESPONSE_MESSAGE__INIT;
  *message = init_value;
}
size_t blnd_response_message__get_packed_size
                     (const BlndResponseMessage *message)
{
  assert(message->base.descriptor == &blnd_response_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t blnd_response_message__pack
                     (const BlndResponseMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &blnd_response_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t blnd_response_message__pack_to_buffer
                     (const BlndResponseMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &blnd_response_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BlndResponseMessage *
       blnd_response_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BlndResponseMessage *)
     protobuf_c_message_unpack (&blnd_response_message__descriptor,
                                allocator, len, data);
}
void   blnd_response_message__free_unpacked
                     (BlndResponseMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &blnd_response_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor blnd_status__field_descriptors[3] =
{
  {
    "state",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(BlndStatus, state),
    &blnd_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "voltage",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BlndStatus, voltage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BlndStatus, position),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blnd_status__field_indices_by_name[] = {
  2,   /* field[2] = position */
  0,   /* field[0] = state */
  1,   /* field[1] = voltage */
};
static const ProtobufCIntRange blnd_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor blnd_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "BlndStatus",
  "BlndStatus",
  "BlndStatus",
  "",
  sizeof(BlndStatus),
  3,
  blnd_status__field_descriptors,
  blnd_status__field_indices_by_name,
  1,  blnd_status__number_ranges,
  (ProtobufCMessageInit) blnd_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor blnd_logging__field_descriptors[1] =
{
  {
    "logmsg",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(BlndLogging, logmsg),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blnd_logging__field_indices_by_name[] = {
  0,   /* field[0] = logmsg */
};
static const ProtobufCIntRange blnd_logging__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor blnd_logging__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "BlndLogging",
  "BlndLogging",
  "BlndLogging",
  "",
  sizeof(BlndLogging),
  1,
  blnd_logging__field_descriptors,
  blnd_logging__field_indices_by_name,
  1,  blnd_logging__number_ranges,
  (ProtobufCMessageInit) blnd_logging__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor blnd_available__field_descriptors[1] =
{
  {
    "available",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(BlndAvailable, available),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blnd_available__field_indices_by_name[] = {
  0,   /* field[0] = available */
};
static const ProtobufCIntRange blnd_available__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor blnd_available__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "BlndAvailable",
  "BlndAvailable",
  "BlndAvailable",
  "",
  sizeof(BlndAvailable),
  1,
  blnd_available__field_descriptors,
  blnd_available__field_indices_by_name,
  1,  blnd_available__number_ranges,
  (ProtobufCMessageInit) blnd_available__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor blnd_operation_message__field_descriptors[5] =
{
  {
    "destAddress",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(BlndOperationMessage, destaddress),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "destSubnet",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(BlndOperationMessage, destsubnet),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "senderAddress",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(BlndOperationMessage, senderaddress),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msgId",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(BlndOperationMessage, msgid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "operation",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(BlndOperationMessage, operation),
    &blnd_operation__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blnd_operation_message__field_indices_by_name[] = {
  0,   /* field[0] = destAddress */
  1,   /* field[1] = destSubnet */
  3,   /* field[3] = msgId */
  4,   /* field[4] = operation */
  2,   /* field[2] = senderAddress */
};
static const ProtobufCIntRange blnd_operation_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor blnd_operation_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "BlndOperationMessage",
  "BlndOperationMessage",
  "BlndOperationMessage",
  "",
  sizeof(BlndOperationMessage),
  5,
  blnd_operation_message__field_descriptors,
  blnd_operation_message__field_indices_by_name,
  1,  blnd_operation_message__number_ranges,
  (ProtobufCMessageInit) blnd_operation_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor blnd_response_message__field_descriptors[8] =
{
  {
    "destAddress",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(BlndResponseMessage, destaddress),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "destSubnet",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(BlndResponseMessage, destsubnet),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "senderAddress",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(BlndResponseMessage, senderaddress),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msgId",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(BlndResponseMessage, msgid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "response",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(BlndResponseMessage, response),
    &blnd_response__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(BlndResponseMessage, proto_case),
    offsetof(BlndResponseMessage, state),
    &blnd_status__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "logging",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(BlndResponseMessage, proto_case),
    offsetof(BlndResponseMessage, logging),
    &blnd_logging__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "avail",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(BlndResponseMessage, proto_case),
    offsetof(BlndResponseMessage, avail),
    &blnd_available__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned blnd_response_message__field_indices_by_name[] = {
  7,   /* field[7] = avail */
  0,   /* field[0] = destAddress */
  1,   /* field[1] = destSubnet */
  6,   /* field[6] = logging */
  3,   /* field[3] = msgId */
  4,   /* field[4] = response */
  2,   /* field[2] = senderAddress */
  5,   /* field[5] = state */
};
static const ProtobufCIntRange blnd_response_message__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 10, 5 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor blnd_response_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "BlndResponseMessage",
  "BlndResponseMessage",
  "BlndResponseMessage",
  "",
  sizeof(BlndResponseMessage),
  8,
  blnd_response_message__field_descriptors,
  blnd_response_message__field_indices_by_name,
  2,  blnd_response_message__number_ranges,
  (ProtobufCMessageInit) blnd_response_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue blnd_operation__enum_values_by_number[8] =
{
  { "CMD_OPEN", "BLND_OPERATION__CMD_OPEN", 0 },
  { "CMD_CLOSE", "BLND_OPERATION__CMD_CLOSE", 1 },
  { "CMD_ENABLE_WIFI", "BLND_OPERATION__CMD_ENABLE_WIFI", 2 },
  { "CMD_DISABLE_WIFI", "BLND_OPERATION__CMD_DISABLE_WIFI", 3 },
  { "CMD_OTA", "BLND_OPERATION__CMD_OTA", 4 },
  { "CMD_STATUS", "BLND_OPERATION__CMD_STATUS", 5 },
  { "CMD_STOP", "BLND_OPERATION__CMD_STOP", 6 },
  { "CMD_IDLE", "BLND_OPERATION__CMD_IDLE", 7 },
};
static const ProtobufCIntRange blnd_operation__value_ranges[] = {
{0, 0},{0, 8}
};
static const ProtobufCEnumValueIndex blnd_operation__enum_values_by_name[8] =
{
  { "CMD_CLOSE", 1 },
  { "CMD_DISABLE_WIFI", 3 },
  { "CMD_ENABLE_WIFI", 2 },
  { "CMD_IDLE", 7 },
  { "CMD_OPEN", 0 },
  { "CMD_OTA", 4 },
  { "CMD_STATUS", 5 },
  { "CMD_STOP", 6 },
};
const ProtobufCEnumDescriptor blnd_operation__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "BlndOperation",
  "BlndOperation",
  "BlndOperation",
  "",
  8,
  blnd_operation__enum_values_by_number,
  8,
  blnd_operation__enum_values_by_name,
  1,
  blnd_operation__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue blnd_response__enum_values_by_number[3] =
{
  { "RESP_STATUS", "BLND_RESPONSE__RESP_STATUS", 0 },
  { "RESP_LOG", "BLND_RESPONSE__RESP_LOG", 1 },
  { "RESP_AVAILABLE", "BLND_RESPONSE__RESP_AVAILABLE", 2 },
};
static const ProtobufCIntRange blnd_response__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex blnd_response__enum_values_by_name[3] =
{
  { "RESP_AVAILABLE", 2 },
  { "RESP_LOG", 1 },
  { "RESP_STATUS", 0 },
};
const ProtobufCEnumDescriptor blnd_response__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "BlndResponse",
  "BlndResponse",
  "BlndResponse",
  "",
  3,
  blnd_response__enum_values_by_number,
  3,
  blnd_response__enum_values_by_name,
  1,
  blnd_response__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue blnd_state__enum_values_by_number[5] =
{
  { "BLINDS_MQTT_OPEN", "BLND_STATE__BLINDS_MQTT_OPEN", 0 },
  { "BLINDS_MQTT_OPENING", "BLND_STATE__BLINDS_MQTT_OPENING", 1 },
  { "BLINDS_MQTT_CLOSING", "BLND_STATE__BLINDS_MQTT_CLOSING", 2 },
  { "BLINDS_MQTT_CLOSED", "BLND_STATE__BLINDS_MQTT_CLOSED", 3 },
  { "BLINDS_MQTT_STOPPED", "BLND_STATE__BLINDS_MQTT_STOPPED", 4 },
};
static const ProtobufCIntRange blnd_state__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex blnd_state__enum_values_by_name[5] =
{
  { "BLINDS_MQTT_CLOSED", 3 },
  { "BLINDS_MQTT_CLOSING", 2 },
  { "BLINDS_MQTT_OPEN", 0 },
  { "BLINDS_MQTT_OPENING", 1 },
  { "BLINDS_MQTT_STOPPED", 4 },
};
const ProtobufCEnumDescriptor blnd_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "BlndState",
  "BlndState",
  "BlndState",
  "",
  5,
  blnd_state__enum_values_by_number,
  5,
  blnd_state__enum_values_by_name,
  1,
  blnd_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
